./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./build.sh
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
cd C:\Users\WILLIAM\Downloads\tutorial18
./build.sh
./build.sh
./build.sh
cd test/
cd tutorial18/
./make
make
./compile.sh
make test
make test
./build.sh
./shader_program.exe 
./build.sh
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./build.sh
./build.sh
./build.sh
./build.sh
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./build.sh
./shader_program.exe 
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./build.sh
./build.sh
./shader_program.exe 
./build.sh
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./build.sh
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./build.sh
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./shader_program.exe 
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe
./build.sh
./shader_program.exe
./build.sh
./shader_program.exe
./build.sh
./shader_program.exe
./build.sh
./shader_program.exe
./build.sh
./shader_program.exe
./build.sh
./shader_program.exe
./build.sh
./shader_program.exe
./build.sh
./shader_program.exe
./build.sh
./shader_program.exe
./shader_program.exe
./build.sh
./shader_program.exe
./build.sh
./shader_program.exe
./build.sh
./shader_program.exe
./build.sh
./build.sh
./build.sh
./shader_program.exe
./build.sh
./shader_program.exe
./build.sh
./shader_program.exe
 
./build.sh
 
./shader_program.exe
./build.sh
./shader_program.exe
./build.sh
./shader_program.exe
./build.sh
./shader_program.exe
./build.sh
./shader_program.exe
./build.sh
./shader_program.exe
./build.sh
./shader_program.exe
./build.sh
./shader_program.exe
./build.sh
./shader_program.exe
./build.sh
./shader_program.exe
./build.sh
./shader_program.exe
./build.sh
./shader_program.exe
./build.sh
./shader_program.exe
./build.sh
./shader_program.exe
./build.sh
./shader_program.exe
./build.sh
./shader_program.exe
./build.sh
./shader_program.exe
./build.sh
./shader_program.exe
./build.sh
./shader_program.exe
./build.sh
./shader_program.exe
./build.sh
./shader_program.exe
./build.sh
./shader_program.exe
./build.sh
./shader_program.exe
./build.sh
./shader_program.exe
./build.sh
./shader_program.exe
./shader_program.exe
./shader_program.exe
./build.sh
./shader_program.exe
./build.sh
./shader_program.exe
./build.sh
./shader_program.exe
./build.sh
./shader_program.exe
./build.sh
./build.sh
./build.sh
./build.sh
./shader_program.exe
./build.sh
./shader_program.exe
./build.sh
./shader_program.exe
./build.sh
./shader_program.exe
./build.sh
./build.sh
./shader_program.exe
./build.sh
./shader_program.exe
./build.sh
./shader_program.exe
./build.sh
./shader_program.exe
./build.sh
./shader_program.exe
./build.sh
./shader_program.exe
./build.sh
./shader_program.exe
./build.sh
./build.sh
./build.sh
./build.sh
./build.sh
./build.sh
./shader_program.exe
./build.sh
./shader_program.exe
./build.sh
./build.sh
./build.sh
./build.sh
./shader_program.exe
./build.sh
./build.sh
./shader_program.exe
./build.sh
./shader_program.exe
./build.sh
./shader_program.exe
./build.sh
./shader_program.exe
./build.sh
./shader_program.exe
./build.sh
./shader_program.exe
./build.sh
./shader_program.exe
./build.sh
./shader_program.exe
./build.sh
./shader_program.exe
./build.sh
./shader_program.exe
./build.sh
./shader_program.exe
./build.sh
./shader_program.exe
./build.sh
./shader_program.exe
./build.sh
./shader_program.exe
./build.sh
./shader_program.exe
./build.sh
./shader_program.exe
./build.sh
./shader_program.exe
./build.sh
./build.sh
./build.sh
./build.sh
./build.sh
./build.sh
./build.sh
./build.sh
./build.sh
./build.sh
./build.sh
./build.sh
./build.sh
./build.sh
./build.sh
./build.sh
./build.sh
ls
./shader_program.exe 
ls
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./shader_program.exe 
ls
./build.sh
./shader_program.exe 
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
./build.sh
./shader_program.exe 
